2021-01-28 04:09:06.228310: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/yangsam/.local/lib/python3.7/site-packages/deepxde/maps/resnet.py:75: dense (from tensorflow.python.keras.legacy_tf_layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From /home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/keras/legacy_tf_layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
2021-01-28 04:09:14.982824: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-28 04:09:14.992729: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2900000000 Hz
2021-01-28 04:09:14.993280: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5555596f1050 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-28 04:09:14.993295: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-01-28 04:09:14.998323: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-01-28 04:09:18.393501: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5555596f3740 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-01-28 04:09:18.393697: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-SXM2-32GB, Compute Capability 7.0
2021-01-28 04:09:18.393703: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): Tesla V100-SXM2-32GB, Compute Capability 7.0
2021-01-28 04:09:18.393707: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): Tesla V100-SXM2-32GB, Compute Capability 7.0
2021-01-28 04:09:18.393710: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (3): Tesla V100-SXM2-32GB, Compute Capability 7.0
2021-01-28 04:09:18.399874: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:1a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-01-28 04:09:18.401722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:1c:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-01-28 04:09:18.403511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 2 with properties: 
pciBusID: 0000:88:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-01-28 04:09:18.405285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 3 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2021-01-28 04:09:18.405314: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-28 04:09:18.409177: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-01-28 04:09:18.412256: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-01-28 04:09:18.413973: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-01-28 04:09:18.417253: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-01-28 04:09:18.419857: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-01-28 04:09:18.425616: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-01-28 04:09:18.439711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1, 2, 3
2021-01-28 04:09:18.439738: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-28 04:09:21.016924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-28 04:09:21.016954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 2 3 
2021-01-28 04:09:21.016960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N Y Y Y 
2021-01-28 04:09:21.016964: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   Y N Y Y 
2021-01-28 04:09:21.016968: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 2:   Y Y N Y 
2021-01-28 04:09:21.016972: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 3:   Y Y Y N 
2021-01-28 04:09:21.026305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30132 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:1a:00.0, compute capability: 7.0)
2021-01-28 04:09:21.028580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30132 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:1c:00.0, compute capability: 7.0)
2021-01-28 04:09:21.030753: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 30132 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-32GB, pci bus id: 0000:88:00.0, compute capability: 7.0)
2021-01-28 04:09:21.032902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 30132 MB memory) -> physical GPU (device: 3, name: Tesla V100-SXM2-32GB, pci bus id: 0000:8a:00.0, compute capability: 7.0)
Traceback (most recent call last):
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 1135, in binary_op_wrapper
    out = r_op(x)
TypeError: 'Tensor' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HX.py", line 112, in <module>
    main()
  File "HX.py", line 74, in main
    model.compile( "adam", lr=1e-4, loss_weights=[1e-6, 1e-6, 1e-6])
  File "/home/yangsam/.local/lib/python3.7/site-packages/deepxde/utils.py", line 52, in wrapper
    result = f(*args, **kwargs)
  File "/home/yangsam/.local/lib/python3.7/site-packages/deepxde/model.py", line 94, in compile
    self.losses *= loss_weights
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 1140, in binary_op_wrapper
    raise e
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 1124, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 1456, in _mul_dispatch
    return multiply(x, y, name=name)
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 508, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6176, in mul
    "Mul", x=x, y=y, name=name)
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1975, in __init__
    control_input_ops, op_def)
  File "/home/yangsam/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1815, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 8 and 3 for '{{node mul_4}} = Mul[T=DT_DOUBLE](packed, mul_4/y)' with input shapes: [8], [3].
